export const TEMPLATES = [
  {
    id: 'one-does-not-simply',
    name: 'One Does Not Simply',
    referenceUrl: 'https://i.imgflip.com/1bij.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Setup', defaultText: 'One does not simply' },
      { id: 'bottom', label: 'Punchline', defaultText: 'Walk into Mordor' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'batman-slapping-robin',
    name: 'Batman Slapping Robin',
    referenceUrl: 'https://i.imgflip.com/9ehk.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Bad take', defaultText: 'But what if we—' },
      { id: 'bottom', label: 'Correction', defaultText: 'NO.' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'distracted-boyfriend',
    name: 'Distracted Boyfriend',
    referenceUrl: 'https://i.imgflip.com/1ur9b0.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Distraction', defaultText: 'New shiny thing' },
      { id: 'bottom', label: 'Reality', defaultText: 'What I should be doing' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'your-face-when',
    name: 'Your Face When',
    referenceUrl: 'https://i.imgflip.com/3oevdk.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Situation', defaultText: 'Your face when' },
      { id: 'bottom', label: 'Punchline', defaultText: 'The meeting could have been an email' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'woman-yelling-at-cat',
    name: 'Woman Yelling at Cat',
    referenceUrl: 'https://i.imgflip.com/345v97.jpg',
    layout: 'split-horizontal',
    photoPlacement: 'zone',
    textZones: [
      { id: 'top', label: 'Accusation', defaultText: 'You said you\'d...' },
      { id: 'bottom', label: 'Defense', defaultText: 'I literally did not' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'two-buttons',
    name: 'Two Buttons',
    referenceUrl: 'https://i.imgflip.com/1g8my4.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Option A', defaultText: 'Do the thing' },
      { id: 'bottom', label: 'Option B', defaultText: 'Also do the thing' },
    ],
    overlayStyle: 'editorial',
  },
  {
    id: 'expanding-brain',
    name: 'Expanding Brain',
    referenceUrl: 'https://i.imgflip.com/1jwhww.jpg',
    layout: 'stacked',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Small brain', defaultText: 'Normal approach' },
      { id: 'bottom', label: 'Galaxy brain', defaultText: 'Ascended take' },
    ],
    overlayStyle: 'editorial',
  },
  {
    id: 'change-my-mind',
    name: 'Change My Mind',
    referenceUrl: 'https://i.imgflip.com/24y43o.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Hot take', defaultText: 'Controversial opinion' },
      { id: 'bottom', label: 'Challenge', defaultText: 'Change my mind' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'waiting-skeleton',
    name: 'Waiting Skeleton',
    referenceUrl: 'https://i.imgflip.com/2fm6x.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Waiting for', defaultText: 'Me waiting for...' },
      { id: 'bottom', label: 'What', defaultText: 'Something that will never happen' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'hide-the-pain-harold',
    name: 'Hide the Pain Harold',
    referenceUrl: 'https://i.imgflip.com/gk5el.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Situation', defaultText: 'When everything goes wrong' },
      { id: 'bottom', label: 'Mask', defaultText: '*smiles through the pain*' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'left-exit-12',
    name: 'Left Exit 12',
    referenceUrl: 'https://i.imgflip.com/22bdq6.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Responsible choice', defaultText: 'The right thing to do' },
      { id: 'bottom', label: 'Actual choice', defaultText: 'The unhinged move' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'disaster-girl',
    name: 'Disaster Girl',
    referenceUrl: 'https://i.imgflip.com/23ls.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Setup', defaultText: 'When you cause chaos' },
      { id: 'bottom', label: 'Reaction', defaultText: 'And enjoy every second' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'blue-pill-red-pill',
    name: 'Blue Pill Red Pill',
    referenceUrl: 'https://i.imgflip.com/1e4lu0.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Blue pill', defaultText: 'Stay comfortable' },
      { id: 'bottom', label: 'Red pill', defaultText: 'Face the harsh truth' },
    ],
    overlayStyle: 'editorial',
  },
  {
    id: 'is-this-a-pigeon',
    name: 'Is This a Pigeon?',
    referenceUrl: 'https://i.imgflip.com/1o00in.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Confusion', defaultText: 'Is this a...?' },
      { id: 'bottom', label: 'Wrong label', defaultText: 'Absolutely not what it is' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'roll-safe',
    name: 'Roll Safe',
    referenceUrl: 'https://i.imgflip.com/1h7in3.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Galaxy brain logic', defaultText: 'Can\'t fail' },
      { id: 'bottom', label: 'Flawed reasoning', defaultText: 'If you never try' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'monkey-puppet',
    name: 'Monkey Puppet',
    referenceUrl: 'https://i.imgflip.com/2gnnjh.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Awkward moment', defaultText: 'When you get caught' },
      { id: 'bottom', label: 'Reaction', defaultText: '*looks away nervously*' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'uno-draw-25',
    name: 'UNO Draw 25',
    referenceUrl: 'https://i.imgflip.com/3lmzyx.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Simple task', defaultText: 'Just do the easy thing' },
      { id: 'bottom', label: 'Refusal', defaultText: 'Or draw 25' },
    ],
    overlayStyle: 'editorial',
  },
  {
    id: 'grandma-internet',
    name: 'Grandma Finds the Internet',
    referenceUrl: 'https://i.imgflip.com/1bhw.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Discovery', defaultText: 'Just found out about...' },
      { id: 'bottom', label: 'Reaction', defaultText: 'This changes everything' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'success-kid',
    name: 'Success Kid',
    referenceUrl: 'https://i.imgflip.com/1bhk.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'Challenge', defaultText: 'Attempted the impossible' },
      { id: 'bottom', label: 'Victory', defaultText: 'Nailed it' },
    ],
    overlayStyle: 'classic',
  },
  {
    id: 'pov-first-day-office',
    name: 'POV: First Day in Office',
    referenceUrl: 'https://imgflip.com/s/meme/First-Day-On-The-Internet-Kid.jpg',
    layout: 'single',
    photoPlacement: 'background',
    textZones: [
      { id: 'top', label: 'POV setup', defaultText: 'POV: First day in office' },
      { id: 'bottom', label: 'Reality', defaultText: 'Already planning my resignation' },
    ],
    overlayStyle: 'editorial',
  },
]

export function getTemplateById(id) {
  return TEMPLATES.find((t) => t.id === id) || null
}
